// Модул: Конфигурация на коефициенти и етикети
// Описание: Дефинира нормализирани ключове за оценки, етикети за показване и групи (SLOT_GROUPS),
//   които позволяват алтернативни източници за един и същ предмет (напр. ДЗИ/Изпит/Диплома).
// Вход: няма
// Изход: константи (напр. FIELD_LABELS, SLOT_GROUPS) използвани в калкулатора и UI
// Бележки: Ключовете са изведени от унифицирани данни на университети; промените влияят върху UI.

const COEFFICIENT_KEYS = [
  "angliiski_ezik", "bel", "bel_plus_cert_angliyski_b2", "bio", "bio_udostoverenie",
  "bonifikaciq", "chu_ezik", "contest_elementarna_mat_boyanov", "diploma",
  "diploma_semestrial", "diploma_state_exams", "diploma_bel", "diploma_mat", "diploma_fiz", "diploma_geo",
  "dzi1_angliiski", "dzi1_bel", "dzi1_bio",
  "dzi1_chu_ezik", "dzi1_fil", "dzi1_fiz", "dzi1_geo", "dzi1_him", "dzi1_informatika",
  "dzi1_ist", "dzi1_it", "dzi1_mat", "dzi1_predpriemachestvo", "dzi2_angliiski", "dzi2_bel",
  "dzi2_bio", "dzi2_chu_ezik", "dzi2_drug_predmet", "dzi2_fil", "dzi2_fiz", "dzi2_geo",
  "dzi2_him", "dzi2_informatika", "dzi2_ist", "dzi2_it", "dzi2_mat", "dzi_angliiski",
  "dzi_angliyski_b1", "dzi_angliyski_b2", "dzi_arabski", "dzi_bel", "dzi_bel_cert_b1",
  "dzi_bel_cert_italianski_b2", "dzi_bel_dele_b1", "dzi_bel_dele_b2plus", "dzi_bio",
  "dzi_bio_obshto", "dzi_bio_profil", "dzi_chu_ezik", "dzi_chu_ezik_b1", "dzi_chu_ezik_b2",
  "dzi_chu_ezik_cert_b1", "dzi_chu_ezik_cert_frenski_b2", "dzi_chu_ezik_cert_nemski_b1",
  "dzi_chu_ezik_cert_nemski_b2_plus", "dzi_chu_ezik_dele_b1_combo",
  "dzi_fil", "dzi_fiz", "dzi_fizika", "dzi_geo",
  "dzi_him", "dzi_hим_obshto",
  "dzi_him_profil", "dzi_himiq", "dzi_informatika", "dzi_inf", "dzi_ist", "dzi_istoriq",
  "dzi_it", "dzi_kitayski", "dzi_kitayski_b2", "dzi_koreiski", "dzi_latin", "dzi_mat",
  "dzi_matematika", "dzi_muz", "dzi_obsht", "dzi_obshtoobrazovatelen_predmet",
  "dzi_portugалски", "dzi_portugalski", "dzi_predpriemachestvo", "dzi_profesiq", "dzi_ris",
  "dzi_rumunski", "dzi_turski", "dzi_yaponski", "ese_obsht_tema", "etika_pravo", "exam_bel",
  "exam_bio", "exam_chu", "exam_fiz", "exam_geo", "exam_him", "exam_informatika", "exam_ist",
  "exam_mat", "exam_muz", "exam_ris",
  "fil", "fiz", "fiz_vazpitanie", "geo", "himija", "him", "informatika",
  "ist", "it", "izpit_drugo_vu", "konkursen_izpit_1", "konkursen_izpit_2", "logika_psihologiya",
  "mat", "muz", "muzika", "obsht_uspeh", "obshtoobrazovatelen_test", "obshtestvoznanie",
  "olympiad_laureate_it", "olympiad_laureate_mat_inf", "olympiad_winner_it",
  "olympiad_winner_mat_inf", "portfolio", "predpriemachestvo", "profesionalna_kvalifikaciq",
  "prof_kv", "psihologiya_na_lichnostta", "socialna_psihologiya", "svqt_i_lichnost",
  "tournament", "vtor_dzi_drug_predmet",
  "dzi_nai_visoka", "dzi_profilirasht_predmet", "eakt_ocenka", "exam_angliiski",
  "exam_angliyski", "exam_etika", "exam_fizika", "exam_iq", "exam_phys", "exam_ris_1",
  "exam_ris_2", "exam_skulptirane", "exam_sport", "exam_test", "grazhdansko_obrazovanie",
  "him_udostoverenie", "hsk4_combo", "istoriq_diploma", "izpit_bel",
  "matematika", "obsht_prirodonauchen_test", "obsht_tehnicheski_test", "ocenka_matematika",
  "prakticheski_izpit_horeografiq", "profilirasht_predmet", "psihologicheska_ocenka", "ris",
  "risuvane_cvetna_kompoziciq", "risuvane_obemno_prostranstvena_kompoziciq",
  "risuvane_perspektiva", "stop_test", "subesedvane", "test_informatika", "test_pravo",
  "topik3_combo", "zdipp_lazerna_i_optichna_tehnika", "zdipp_ochna_optika",
  "zdipp_programno_osiguryavane", "zdippk_bibliotekoznanie", "zdippk_delovodstvo_arhiv",
  "zdippk_fotografiya", "zdippk_ikonomichesko_informacionno_osigurqvane",
  "zdippk_poligrafiya", "zdippk_posrednik_trudova_borsa", "zdippk_satrudnik_socialni_deinosti",
  "zdippk_tekstoobrabotka", "zdippk_turizam", "zdippk_veterinaren_tehnik", "zrelosten_bel",
  "exam_nemski", "exam_frenski", "exam_ispanski", "exam_italianski", "exam_ruski",
  "dzi1_nemski", "dzi1_frenski", "dzi1_ispanski", "dzi1_italianski", "dzi1_ruski",
  "dzi2_nemski", "dzi2_frenski", "dzi2_ispanski", "dzi2_italianski", "dzi2_ruski",
  "dzi_nemski", "dzi_frenski", "dzi_ispanski", "dzi_italianski", "dzi_ruski",
  "dzi_iztochno_hrist", "zdippk_muzika", "zdippk_iztochno_hrist",
  // Профилиращи ДЗИ (coef 2.4 при ВТУ и др.)
  "dzi_profil_angliiski", "dzi_profil_chu", "dzi_profil_filosofiya", "dzi_profil_frenski",
  "dzi_profil_geografiya", "dzi_profil_inf", "dzi_profil_ispanski", "dzi_profil_ist",
  "dzi_profil_it", "dzi_profil_mat", "dzi_profil_nemski", "dzi_profil_predp", "dzi_profil_ruski"
];

const FIELD_LABELS = {
  angliiski_ezik: "Диплома: Английски език",
  bel: "Диплома: БЕЛ",
  diploma_bel: "Диплома: БЕЛ",
  bel_plus_cert_angliyski_b2: "БЕЛ + Сертификат английски B2",
  bio: "Диплома: Биология",
  bio_udostoverenie: "Биология удостоверение",
  bonifikaciq: "Бонификация",
  chu_ezik: "Диплома: Чужд език",
  contest_elementarna_mat_boyanov: "Състезание елементарна мат (Боянов)",
  diploma: "Диплома",
  diploma_semestrial: "Семестриален успех",
  diploma_state_exams: "Държавни изпити",
  dzi1_angliiski: "ДЗИ¹ Английски език",
  dzi1_bel: "ДЗИ¹ БЕЛ",
  dzi1_bio: "ДЗИ¹ Биология",
  dzi1_chu_ezik: "ДЗИ¹ Чужд език",
  dzi1_fil: "ДЗИ¹ Философия",
  dzi1_fiz: "ДЗИ¹ Физика",
  dzi1_geo: "ДЗИ¹ География",
  dzi1_him: "ДЗИ¹ Химия",
  dzi1_informatika: "ДЗИ¹ Информатика",
  dzi1_ist: "ДЗИ¹ История",
  dzi1_it: "ДЗИ¹ ИТ",
  dzi1_mat: "ДЗИ¹ Математика",
  dzi1_predpriemachestvo: "ДЗИ¹ Предприемачество",
  dzi2_angliiski: "ДЗИ² Английски език",
  dzi2_bel: "ДЗИ² БЕЛ",
  dzi2_bio: "ДЗИ² Биология",
  dzi2_chu_ezik: "ДЗИ² Чужд език",
  dzi2_drug_predmet: "ДЗИ² друг предмет",
  dzi2_fil: "ДЗИ² Философия",
  dzi2_fiz: "ДЗИ² Физика",
  dzi2_geo: "ДЗИ² География",
  dzi2_him: "ДЗИ² Химия",
  dzi2_informatika: "ДЗИ² Информатика",
  dzi2_ist: "ДЗИ² История",
  dzi2_it: "ДЗИ² ИТ",
  dzi2_mat: "ДЗИ² Математика",
  dzi_angliiski: "ДЗИ Английски език",
  dzi_angliyski_b1: "ДЗИ Английски език B1",
  dzi_angliyski_b2: "ДЗИ Английски език B2",
  dzi_arabski: "ДЗИ Арабски език",
  dzi_bel: "ДЗИ БЕЛ",
  dzi_bel_cert_b1: "ДЗИ БЕЛ + Сертификат B1",
  dzi_bel_cert_italianski_b2: "ДЗИ БЕЛ + Сертификат италиански B2",
  dzi_bel_dele_b1: "ДЗИ БЕЛ + DELE B1",
  dzi_bel_dele_b2plus: "ДЗИ БЕЛ + DELE B2+",
  dzi_bio: "ДЗИ Биология",
  dzi_bio_obshto: "ДЗИ Биология (общо)",
  dzi_bio_profil: "ДЗИ Биология (профил)",
  dzi_chu_ezik: "ДЗИ Чужд език",
  dzi_chu_ezik_b1: "ДЗИ Чужд език B1",
  dzi_chu_ezik_b2: "ДЗИ Чужд език B2",
  dzi_chu_ezik_cert_b1: "ДЗИ Чужд език + Сертификат B1",
  dzi_chu_ezik_cert_frenski_b2: "ДЗИ Чужд език + Сертификат френски B2",
  dzi_chu_ezik_cert_nemski_b1: "ДЗИ Чужд език + Сертификат немски B1",
  dzi_chu_ezik_cert_nemski_b2_plus: "ДЗИ Чужд език + Сертификат немски B2+",
  dzi_chu_ezik_dele_b1_combo: "ДЗИ Чужд език + DELE B1 (комбо)",
  dzi_fil: "ДЗИ Философия",
  dzi_fiz: "ДЗИ Физика",
  dzi_fizika: "ДЗИ Физика",
  dzi_geo: "ДЗИ География",
  dzi_him: "ДЗИ Химия",
  dzi_him_obshto: "ДЗИ Химия (общо)",
  dzi_him_profil: "ДЗИ Химия (профил)",
  dzi_himiq: "ДЗИ Химия",
  dzi_informatika: "ДЗИ Информатика",
  dzi_inf: "ДЗИ Информатика",
  dzi_ist: "ДЗИ История",
  dzi_istoriq: "ДЗИ История",
  dzi_it: "ДЗИ ИТ",
  dzi_kitayski: "ДЗИ Китайски език",
  dzi_kitayski_b2: "ДЗИ Китайски език B2",
  dzi_koreiski: "ДЗИ Корейски език",
  dzi_latin: "ДЗИ Латински език",
  dzi_mat: "ДЗИ Математика",
  dzi_matematika: "ДЗИ Математика",
  dzi_muz: "ДЗИ Музика",
  dzi_obsht: "ДЗИ Общообразователен",
  dzi_obshtoobrazovatelen_predmet: "ДЗИ Общообразователен предмет",
  dzi_portugалски: "ДЗИ Португалски език",
  dzi_portugalski: "ДЗИ Португалски език",
  dzi_predpriemachestvo: "ДЗИ Предприемачество",
  dzi_profesiq: "ДЗИ Професия",
  dzi_ris: "ДЗИ Рисуване",
  dzi_rumunski: "ДЗИ Румънски език",
  dzi_turski: "ДЗИ Турски език",
  dzi_yaponski: "ДЗИ Японски език",
  ese_obsht_tema: "Есе на обществена тема",
  etika_pravo: "Диплома: Етика и право",
  exam_bel: "Изпит по БЕЛ",
  exam_bio: "Изпит по биология",
  exam_chu: "Изпит по чужд език",
  exam_fiz: "Изпит по физика",
  exam_geo: "Изпит по география",
  exam_him: "Изпит по химия",
  exam_informatika: "Изпит по информатика",
  exam_ist: "Изпит по история",
  exam_mat: "Изпит по математика",
  exam_muz: "Изпит по музика",
  exam_ris: "Изпит по рисуване",
  fil: "Диплома: Философия",
  fiz: "Диплома: Физика",
  fiz_vazpitanie: "Диплома: Физическо възпитание",
  geo: "Диплома: География",
  himija: "Диплома: Химия",
  him: "Диплома: Химия",
  informatika: "Диплома: Информатика",
  ist: "Диплома: История",
  it: "Диплома: ИТ",
  izpit_drugo_vu: "Изпит друго ВУ",
  konkursen_izpit_1: "Конкурсен изпит",
  konkursen_izpit_2: "Конкурсен изпит 2",
  logika_psihologiya: "Диплома: Логика и психология",
  mat: "Диплома: Математика",
  muz: "Диплома: Музика",
  muzika: "Диплома: Музика",
  obsht_uspeh: "Общ успех от диплома",
  obshtoobrazovatelen_test: "Общообразователен тест",
  obshtestvoznanie: "Диплома: Обществознание",
  olympiad_laureate_it: "Олимпиада (лауреат) ИТ",
  olympiad_laureate_mat_inf: "Олимпиада (лауреат) Мат/Инф",
  olympiad_winner_it: "Олимпиада (победител) ИТ",
  olympiad_winner_mat_inf: "Олимпиада (победител) Мат/Инф",
  portfolio: "Портфолио",
  predpriemachestvo: "Предприемачество",
  profesionalna_kvalifikaciq: "Професионална квалификация",
  prof_kv: "Професионална квалификация",
  psihologiya_na_lichnostta: "Диплома: Психология на личността",
  socialna_psihologiya: "Диплома: Социална психология",
  svqt_i_lichnost: "Диплома: Свят и личност",
  tournament: "Турнир",
  vtor_dzi_drug_predmet: "Втори ДЗИ друг предмет",
  dzi_nai_visoka: "Най-висока ДЗИ",
  dzi_profilirasht_predmet: "ДЗИ профилиращ предмет",
  eakt_ocenka: "ЕАКТ оценка",
  exam_angliiski: "Изпит по английски език",
  exam_angliyski: "Изпит по английски език",
  exam_etika: "Изпит по етика",
  exam_fizika: "Изпит по физика",
  exam_iq: "IQ тест",
  exam_phys: "Изпит по физика",
  exam_ris_1: "Изпит по рисуване 1",
  exam_ris_2: "Изпит по рисуване 2",
  exam_skulptirane: "Изпит по скулптиране",
  exam_sport: "Изпит по спорт",
  exam_test: "Приемен тест",
  grazhdansko_obrazovanie: "Диплома: Гражданско образование",
  him_udostoverenie: "Химия удостоверение",
  hsk4_combo: "HSK4 комбинация",
  istoriq_diploma: "Диплома: История",
  izpit_bel: "Изпит по БЕЛ",
  diploma_mat: "Диплома: Математика",
  diploma_fiz: "Диплома: Физика",
  diploma_geo: "Диплома: География",
  matematika: "Диплома: Математика",
  obsht_prirodonauchen_test: "Общ природонаучен тест",
  obsht_tehnicheski_test: "Общ технически тест",
  ocenka_matematika: "Оценка по математика",
  prakticheski_izpit_horeografiq: "Практически изпит по хореография",
  profilirasht_predmet: "Профилиращ предмет",
  psihologicheska_ocenka: "Психологическа оценка",
  ris: "Рисуване",
  risuvane_cvetna_kompoziciq: "Рисуване цветна композиция",
  risuvane_obemno_prostranstvena_kompoziciq: "Рисуване обемно-пространствена композиция",
  risuvane_perspektiva: "Рисуване перспектива",
  stop_test: "STOP тест",
  subesedvane: "Събеседване",
  test_informatika: "Тест по информатика",
  test_pravo: "Тест по право",
  topik3_combo: "TOPIK3 комбинация",
  zdipp_lazerna_i_optichna_tehnika: "ЗДИПП Лазерна и оптична техника",
  zdipp_ochna_optika: "ЗДИПП Очна оптика",
  zdipp_programno_osiguryavane: "ЗДИПП Програмно осигуряване",
  zdippk_bibliotekoznanie: "ЗДИППК Библиотекознание",
  zdippk_delovodstvo_arhiv: "ЗДИППК Деловодство и архив",
  zdippk_fotografiya: "ЗДИППК Фотография",
  zdippk_ikonomichesko_informacionno_osigurqvane: "ЗДИППК Икономическо информационно осигуряване",
  zdippk_poligrafiya: "ЗДИППК Полиграфия",
  zdippk_posrednik_trudova_borsa: "ЗДИППК Посредник трудова борса",
  zdippk_satrudnik_socialni_deinosti: "ЗДИППК Сътрудник социални дейности",
  zdippk_tekstoobrabotka: "ЗДИППК Текстообработка",
  zdippk_turizam: "ЗДИППК Туризъм",
  zdippk_veterinaren_tehnik: "ЗДИППК Ветеринарен техник",
  zrelosten_bel: "Зрелостен изпит по БЕЛ",
  exam_nemski: "Изпит по немски език",
  exam_frenski: "Изпит по френски език",
  exam_ispanski: "Изпит по испански език",
  exam_italianski: "Изпит по италиански език",
  exam_ruski: "Изпит по руски език",
  dzi1_nemski: "ДЗИ¹ Немски език",
  dzi1_frenski: "ДЗИ¹ Френски език",
  dzi1_ispanski: "ДЗИ¹ Испански език",
  dzi1_italianski: "ДЗИ¹ Италиански език",
  dzi1_ruski: "ДЗИ¹ Руски език",
  dzi2_nemski: "ДЗИ² Немски език",
  dzi2_frenski: "ДЗИ² Френски език",
  dzi2_ispanski: "ДЗИ² Испански език",
  dzi2_italianski: "ДЗИ² Италиански език",
  dzi2_ruski: "ДЗИ² Руски език",
  dzi_nemski: "ДЗИ Немски език",
  dzi_frenski: "ДЗИ Френски език",
  dzi_ispanski: "ДЗИ Испански език",
  dzi_italianski: "ДЗИ Италиански език",
  dzi_ruski: "ДЗИ Руски език",
  dzi_iztochno_hrist: "ДЗИ Източноправославно християнство",
  zdippk_muzika: "ЗДИППК Музика",
  zdippk_iztochno_hrist: "ЗДИППК Източноправославно християнство",
  // Профилиращи ДЗИ (взимат по-висок коефициент при определени специалности)
  dzi_profil_angliiski: "Профилиращ ДЗИ Английски",
  dzi_profil_chu: "Профилиращ ДЗИ Чужд език",
  dzi_profil_filosofiya: "Профилиращ ДЗИ Философия",
  dzi_profil_frenski: "Профилиращ ДЗИ Френски",
  dzi_profil_geografiya: "Профилиращ ДЗИ География",
  dzi_profil_inf: "Профилиращ ДЗИ Информатика",
  dzi_profil_ispanski: "Профилиращ ДЗИ Испански",
  dzi_profil_ist: "Профилиращ ДЗИ История",
  dzi_profil_it: "Профилиращ ДЗИ ИТ",
  dzi_profil_mat: "Профилиращ ДЗИ Математика",
  dzi_profil_nemski: "Профилиращ ДЗИ Немски",
  dzi_profil_predp: "Профилиращ ДЗИ Предприемачество",
  dzi_profil_ruski: "Профилиращ ДЗИ Руски"
};

// Логически групи от коефициенти – помагат при избор на подходящи полета за формули/интерфейс.
const SLOT_GROUPS = {
  // Mathematics group
  math_group: ["exam_mat", "dzi1_mat", "dzi2_mat", "dzi_mat", "dzi_matematika", "mat",
    "dzi_profil_mat",
    "olympiad_winner_mat_inf", "olympiad_laureate_mat_inf",
    "contest_elementarna_mat_boyanov", "tournament"],
  
  // Biology group
  biology_group: ["exam_bio", "dzi1_bio", "dzi2_bio", "dzi_bio", 
    "dzi_bio_obshto", "dzi_bio_profil", "bio", "bio_udostoverenie"],
  
  // Chemistry group
  chemistry_group: ["exam_him", "dzi1_him", "dzi2_him", "dzi_him", 
    "dzi_him_obshto", "dzi_him_profil", "dzi_himiq", "him", "himija"],
  
  // Physics group
  physics_group: ["exam_fiz", "dzi1_fiz", "dzi2_fiz", "dzi_fiz", "dzi_fizika", "fiz"],
  
  // Bulgarian language group
  bulgarian_group: ["exam_bel", "dzi1_bel", "dzi2_bel", "dzi_bel", "bel", "diploma_bel",
    "dzi_bel_cert_b1", "dzi_bel_cert_italianski_b2",
    "dzi_bel_dele_b1", "dzi_bel_dele_b2plus", "bel_plus_cert_angliyski_b2"],
  
  // Foreign languages group
  foreign_languages_group: ["exam_chu", "dzi1_chu_ezik", "dzi2_chu_ezik", "dzi_chu_ezik",
    "dzi_chu_ezik_b1", "dzi_chu_ezik_b2", "chu_ezik",
    "dzi_chu_ezik_cert_b1", "dzi_chu_ezik_cert_frenski_b2", "dzi_chu_ezik_cert_nemski_b1",
    "dzi_chu_ezik_cert_nemski_b2_plus", "dzi_chu_ezik_dele_b1_combo", "dzi_profil_chu"],
  
  // English
  english_group: ["dzi1_angliiski", "dzi2_angliiski", "dzi_angliiski",
    "dzi_angliyski_b1", "dzi_angliyski_b2", "angliiski_ezik",
    "exam_angliiski", "exam_angliyski", "dzi_profil_angliiski"],

  // German
  german_group: ["exam_nemski", "dzi1_nemski", "dzi2_nemski", "dzi_nemski", "dzi_profil_nemski"],

  // French
  french_group: ["exam_frenski", "dzi1_frenski", "dzi2_frenski", "dzi_frenski", "dzi_profil_frenski"],

  // Spanish
  spanish_group: ["exam_ispanski", "dzi1_ispanski", "dzi2_ispanski", "dzi_ispanski", "dzi_profil_ispanski"],

  // Italian
  italian_group: ["exam_italianski", "dzi1_italianski", "dzi2_italianski", "dzi_italianski"],

  // Russian
  russian_group: ["exam_ruski", "dzi1_ruski", "dzi2_ruski", "dzi_ruski", "dzi_profil_ruski"],
  
  // Asian languages
  asian_languages_group: ["dzi_yaponski", "dzi_kitayski", "dzi_kitayski_b2", "dzi_koreiski"],
  
  // Other languages
  other_languages_group: ["dzi_arabski", "dzi_latin", "dzi_rumunski",
    "dzi_portugalski", "dzi_portugалски", "dzi_turski",
    "dzi_iztochno_hrist"],
  
  // IT and Informatics
  it_informatics_group: ["exam_informatika", "dzi1_informatika", "dzi2_informatika",
    "dzi_informatika", "dzi_inf", "informatika", "dzi1_it", "dzi2_it", "dzi_it", "it",
    "test_informatika", "dzi_profil_inf", "dzi_profil_it",
    "olympiad_winner_it", "olympiad_laureate_it"],

  // History
  history_group: ["exam_ist", "dzi1_ist", "dzi2_ist", "dzi_ist", "dzi_istoriq", "ist",
    "istoriq_diploma", "dzi_profil_ist"],

  // Geography
  geography_group: ["exam_geo", "dzi1_geo", "dzi2_geo", "dzi_geo", "geo",
    "dzi_profil_geografiya"],

  // Philosophy
  philosophy_group: ["dzi1_fil", "dzi2_fil", "dzi_fil", "fil",
    "dzi_profil_filosofiya"],

  // Arts
  arts_group: ["exam_muz", "dzi_muz", "muz", "muzika", "exam_ris", "dzi_ris",
    "portfolio", "exam_ris_1", "exam_ris_2", "exam_skulptirane", "ris",
    "risuvane_cvetna_kompoziciq", "risuvane_obemno_prostranstvena_kompoziciq",
    "risuvane_perspektiva", "prakticheski_izpit_horeografiq"],

  // Diploma and general
  diploma_group: ["diploma", "obsht_uspeh", "diploma_semestrial", "diploma_state_exams",
    "diploma_bel", "diploma_mat", "diploma_fiz", "diploma_geo",
    "matematika", "zrelosten_bel", "fiz_vazpitanie"],
  
  // Business
  business_group: ["dzi1_predpriemachestvo", "dzi_predpriemachestvo", "predpriemachestvo",
    "dzi_profil_predp"],
  
  // Professional
  professional_group: ["dzi_profesiq", "profesionalna_kvalifikaciq", "prof_kv",
    "dzi_obshtoobrazovatelen_predmet", "dzi_obsht",
    "zdipp_lazerna_i_optichna_tehnika", "zdipp_ochna_optika",
    "zdipp_programno_osiguryavane", "zdippk_bibliotekoznanie", "zdippk_delovodstvo_arhiv",
    "zdippk_fotografiya", "zdippk_ikonomichesko_informacionno_osigurqvane",
    "zdippk_poligrafiya", "zdippk_posrednik_trudova_borsa", "zdippk_satrudnik_socialni_deinosti",
    "zdippk_tekstoobrabotka", "zdippk_turizam", "zdippk_veterinaren_tehnik",
    "zdippk_muzika", "zdippk_iztochno_hrist"],
  
  // Social sciences
  social_subjects_group: ["etika_pravo", "logika_psihologiya", "obshtestvoznanie",
    "svqt_i_lichnost", "socialna_psihologiya", "psihologiya_na_lichnostta",
    "grazhdansko_obrazovanie", "exam_etika", "psihologicheska_ocenka", "test_pravo"],
  
  // Competition
  competition_group: ["konkursen_izpit_1", "konkursen_izpit_2", "obshtoobrazovatelen_test",
    "ese_obsht_tema", "bonifikaciq", "izpit_drugo_vu", 
    "vtor_dzi_drug_predmet", "dzi2_drug_predmet",
    "exam_iq", "exam_test", "obsht_prirodonauchen_test", "obsht_tehnicheski_test",
    "stop_test", "subesedvane"]
};

export { COEFFICIENT_KEYS, FIELD_LABELS, SLOT_GROUPS };
